### Health Check (Public)
GET {{host}}/{{base_path}}/v1/health

### Robots.txt (Public)
GET {{host}}/robots.txt

### Netdata Token Webhook (Protected)
POST {{host}}/{{base_path}}/v1/{{topic}}/netdata
Content-Type: application/json
Authorization: {{auth}}

< docs/playloads/netdata-token.json

### Netdata Alert Webhook - Critical (Protected)
POST {{host}}/{{base_path}}/v1/{{topic}}/netdata
Content-Type: application/json
Authorization: {{auth}}

< docs/playloads/netdata-alert-critical.json

### Netdata Alert Webhook - Warning (Protected)
POST {{host}}/{{base_path}}/v1/{{topic}}/netdata
Content-Type: application/json
Authorization: {{auth}}

< docs/playloads/netdata-alert-warning.json

### Netdata Alert Webhook - Recovered (Protected)
POST {{host}}/{{base_path}}/v1/{{topic}}/netdata
Content-Type: application/json
Authorization: {{auth}}

< docs/playloads/netdata-alert-recovered.json

### Netdata Reachability Webhook - Unreachable (Protected)
POST {{host}}/{{base_path}}/v1/{{topic}}/netdata
Content-Type: application/json
Authorization: {{auth}}

< docs/playloads/netdata-reachability-unreachable.json

### Netdata Reachability Webhook - Reachable (Protected)
POST {{host}}/{{base_path}}/v1/{{topic}}/netdata
Content-Type: application/json
Authorization: {{auth}}

< docs/playloads/netdata-reachability-reachable.json

### Dump
POST {{host}}/{{base_path}}/v1/dump
Content-Type: application/json
Authorization: {{auth}}

< docs/playloads/netdata-alert-critical.json
